language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
sudo: false
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: GEQ/1chU5SvUVCycyYhe40CCYYSy9G+Fuyq8l+mwvs7la0fOp+webW5w8zg0jQks3O/1oXncRUqMdImsPf8oeM5YkkdiClLYw+TnT/HGpbJLXWoV8SGPr9qtViqLkUf5nQvdw4EJmwtTirdgFPi+YpsJ1BTW07m31z0QAosVjgw=
  file:
    - 'metaphone.js'
    - 'metaphone.min.js'
  on:
    tags: true
